-- Дополнительные фотографии для полных материалов новостей.
--
-- Выполняйте файл целиком в Supabase Dashboard -> SQL Editor.
-- Миграция не изменяет public.news, public.admin_users, bucket news-images
-- или существующие политики этих объектов. Повторный запуск безопасен.

begin;

create table if not exists public.news_photos (
  id bigint generated by default as identity primary key,
  news_id bigint not null
    references public.news(id) on delete cascade,
  image_url text not null
    check (char_length(btrim(image_url)) between 1 and 2048),
  image_path text not null
    check (char_length(btrim(image_path)) between 1 and 1024),
  caption text
    check (caption is null or char_length(caption) <= 500),
  alt_text text
    check (alt_text is null or char_length(alt_text) <= 300),
  sort_order integer not null default 0
    check (sort_order >= 0),
  created_at timestamptz not null default now()
);

create index if not exists news_photos_news_order_idx
  on public.news_photos (news_id, sort_order, created_at);

alter table public.news_photos enable row level security;

revoke all on public.news_photos from anon, authenticated;
grant select on public.news_photos to anon, authenticated;
grant insert, update, delete on public.news_photos to authenticated;
grant usage, select on sequence public.news_photos_id_seq to authenticated;

drop policy if exists "Visitors can read photos from published news"
  on public.news_photos;
create policy "Visitors can read photos from published news"
on public.news_photos
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.news
    where news.id = news_photos.news_id
      and news.published = true
  )
);

drop policy if exists "Admins can manage news photos"
  on public.news_photos;
create policy "Admins can manage news photos"
on public.news_photos
for all
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

commit;
