-- Минимальная схема новостей для сайта Федерации фехтования Томской области.
-- Выполняйте файл целиком в Supabase Dashboard -> SQL Editor.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 200),
  date date not null,
  date_label text check (date_label is null or char_length(date_label) <= 80),
  summary text not null check (char_length(summary) between 1 and 700),
  content text not null check (char_length(content) between 1 and 20000),
  image_url text not null default '',
  image_path text,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists news_published_date_idx
  on public.news (published, date desc, created_at desc);

create or replace function public.set_news_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_news_updated_at on public.news;
create trigger set_news_updated_at
before update on public.news
for each row execute function public.set_news_updated_at();

alter table public.admin_users enable row level security;
alter table public.news enable row level security;

revoke all on public.admin_users from anon, authenticated;
grant select on public.admin_users to authenticated;

revoke all on public.news from anon, authenticated;
grant select on public.news to anon, authenticated;
grant insert, update, delete on public.news to authenticated;
grant usage, select on sequence public.news_id_seq to authenticated;

drop policy if exists "Admin can see own access record" on public.admin_users;
create policy "Admin can see own access record"
on public.admin_users
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Anyone can read published news" on public.news;
create policy "Anyone can read published news"
on public.news
for select
to anon
using (published = true);

drop policy if exists "Admins can read all news" on public.news;
create policy "Admins can read all news"
on public.news
for select
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can create news" on public.news;
create policy "Admins can create news"
on public.news
for insert
to authenticated
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can update news" on public.news;
create policy "Admins can update news"
on public.news
for update
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can delete news" on public.news;
create policy "Admins can delete news"
on public.news
for delete
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'news-images',
  'news-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admins can upload news images" on storage.objects;
create policy "Admins can upload news images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'news-images'
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can delete news images" on storage.objects;
create policy "Admins can delete news images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'news-images'
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

-- Три новости, которые уже находятся в index.html.
insert into public.news
  (title, date, summary, content, image_url, image_path, published)
select
  'Томские фехтовальщики завоевали золото и две бронзы на турнире Любови Шутовой',
  date '2026-05-17',
  'На межрегиональном турнире на призы заслуженного мастера спорта России Любови Шутовой томские спортсмены показали отличные результаты. Захар Пронин стал победителем соревнований среди юношей, Родион Костырев завоевал бронзовую медаль в личном первенстве. Также команда Томской области стала бронзовым призёром командных соревнований.',
  'На межрегиональном турнире на призы заслуженного мастера спорта России Любови Шутовой томские спортсмены показали отличные результаты. Захар Пронин стал победителем соревнований среди юношей, Родион Костырев завоевал бронзовую медаль в личном первенстве. Также команда Томской области стала бронзовым призёром командных соревнований.',
  'images/awards/shutova2026/shutova2026.jpeg',
  null,
  true
where not exists (
  select 1 from public.news
  where title = 'Томские фехтовальщики завоевали золото и две бронзы на турнире Любови Шутовой'
    and date = date '2026-05-17'
);

insert into public.news
  (title, date, summary, content, image_url, image_path, published)
select
  'Первенство Томской области: девушки',
  date '2026-03-14',
  'По итогам соревнований первое место заняла Алина Коренькова, второе место — Анна Мужецкая, третьи места — Вера Бурлевич и Мария Терехина.',
  'По итогам соревнований первое место заняла Алина Коренькова, второе место — Анна Мужецкая, третьи места — Вера Бурлевич и Мария Терехина.',
  'images/awards/tomsk2025/womenu23.jpeg',
  null,
  true
where not exists (
  select 1 from public.news
  where title = 'Первенство Томской области: девушки'
    and date = date '2026-03-14'
);

insert into public.news
  (title, date, date_label, summary, content, image_url, image_path, published)
select
  'Бронза на Кубке Легенд в Уфе',
  date '2025-11-18',
  '15–18 ноября 2025',
  'Томские фехтовальщики заняли 3 место в командном первенстве Кубка Легенд Республики Башкортостан. Состав команды: Пронин Захар, Яновский Александр и Костырев Родион.',
  'Томские фехтовальщики заняли 3 место в командном первенстве Кубка Легенд Республики Башкортостан. Состав команды: Пронин Захар, Яновский Александр и Костырев Родион.',
  'images/awards/ufa2025/parni3mesto.jpg',
  null,
  true
where not exists (
  select 1 from public.news
  where title = 'Бронза на Кубке Легенд в Уфе'
    and date = date '2025-11-18'
);

-- После создания пользователя в Authentication замените адрес и выполните отдельно:
-- insert into public.admin_users (user_id)
-- select id from auth.users where email = 'ADMIN_EMAIL@example.com'
-- on conflict (user_id) do nothing;
