-- Расширение единой админ-панели сайта Федерации фехтования Томской области.
-- Выполняйте файл целиком в Supabase Dashboard -> SQL Editor.
--
-- Миграция добавляет только новые сущности. Она не изменяет существующие
-- public.news, public.admin_users, bucket news-images или их политики.

-- ---------------------------------------------------------------------------
-- Таблицы
-- ---------------------------------------------------------------------------

create table if not exists public.competition_events (
  id bigint generated by default as identity primary key,
  title text not null
    check (char_length(btrim(title)) between 1 and 200),
  start_date date not null,
  end_date date,
  location text not null default ''
    check (char_length(location) <= 200),
  description text not null default ''
    check (char_length(description) <= 2000),
  category_label text not null default ''
    check (char_length(category_label) <= 100),
  short_label text not null default ''
    check (char_length(short_label) <= 12),
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint competition_events_date_range_check
    check (end_date is null or end_date >= start_date)
);

create table if not exists public.competition_results (
  id bigint generated by default as identity primary key,
  competition_date date not null,
  date_label text
    check (date_label is null or char_length(date_label) <= 80),
  title text not null
    check (char_length(btrim(title)) between 1 and 200),
  result_text text not null
    check (char_length(btrim(result_text)) between 1 and 5000),
  category text not null default ''
    check (char_length(category) <= 200),
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gallery_albums (
  id bigint generated by default as identity primary key,
  title text not null
    check (char_length(btrim(title)) between 1 and 200),
  description text not null default ''
    check (char_length(description) <= 2000),
  event_date date,
  published boolean not null default false,
  sort_order integer not null default 0
    check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gallery_photos (
  id bigint generated by default as identity primary key,
  album_id bigint not null
    references public.gallery_albums(id) on delete cascade,
  image_url text not null
    check (char_length(btrim(image_url)) between 1 and 2048),
  image_path text
    check (
      image_path is null
      or char_length(btrim(image_path)) between 1 and 1024
    ),
  caption text not null default ''
    check (char_length(caption) <= 500),
  alt_text text not null default ''
    check (char_length(alt_text) <= 300),
  sort_order integer not null default 0
    check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Только явно разрешённые текстовые поля и ссылки на изображения.
-- Произвольные HTML, CSS, JSON или шаблоны в этой таблице не хранятся.
create table if not exists public.home_content (
  id smallint primary key default 1,
  hero_kicker text not null default ''
    check (char_length(hero_kicker) <= 120),
  hero_title text not null default ''
    check (char_length(hero_title) <= 200),
  hero_subtitle text not null default ''
    check (char_length(hero_subtitle) <= 700),
  hero_image_url text not null default ''
    check (char_length(hero_image_url) <= 2048),
  hero_image_path text
    check (
      hero_image_path is null
      or char_length(btrim(hero_image_path)) between 1 and 1024
    ),
  hero_image_alt text not null default ''
    check (char_length(hero_image_alt) <= 300),
  about_eyebrow text not null default ''
    check (char_length(about_eyebrow) <= 120),
  about_title text not null default ''
    check (char_length(about_title) <= 200),
  about_text text not null default ''
    check (char_length(about_text) <= 5000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint home_content_singleton_check check (id = 1)
);

insert into public.home_content (id)
values (1)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Индексы
-- ---------------------------------------------------------------------------

create index if not exists competition_events_public_date_idx
  on public.competition_events
  (published, start_date, created_at desc);

create index if not exists competition_results_public_date_idx
  on public.competition_results
  (published, competition_date desc, created_at desc);

create index if not exists gallery_albums_public_order_idx
  on public.gallery_albums
  (published, sort_order, event_date desc, created_at desc);

create index if not exists gallery_photos_album_order_idx
  on public.gallery_photos
  (album_id, sort_order, created_at, id);

create unique index if not exists gallery_photos_image_path_key
  on public.gallery_photos (image_path)
  where image_path is not null;

-- ---------------------------------------------------------------------------
-- updated_at
-- ---------------------------------------------------------------------------

create or replace function public.set_site_admin_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_competition_events_updated_at
  on public.competition_events;
create trigger set_competition_events_updated_at
before update on public.competition_events
for each row execute function public.set_site_admin_updated_at();

drop trigger if exists set_competition_results_updated_at
  on public.competition_results;
create trigger set_competition_results_updated_at
before update on public.competition_results
for each row execute function public.set_site_admin_updated_at();

drop trigger if exists set_gallery_albums_updated_at
  on public.gallery_albums;
create trigger set_gallery_albums_updated_at
before update on public.gallery_albums
for each row execute function public.set_site_admin_updated_at();

drop trigger if exists set_gallery_photos_updated_at
  on public.gallery_photos;
create trigger set_gallery_photos_updated_at
before update on public.gallery_photos
for each row execute function public.set_site_admin_updated_at();

drop trigger if exists set_home_content_updated_at
  on public.home_content;
create trigger set_home_content_updated_at
before update on public.home_content
for each row execute function public.set_site_admin_updated_at();

-- ---------------------------------------------------------------------------
-- Права и RLS
-- ---------------------------------------------------------------------------

alter table public.competition_events enable row level security;
alter table public.competition_results enable row level security;
alter table public.gallery_albums enable row level security;
alter table public.gallery_photos enable row level security;
alter table public.home_content enable row level security;

revoke all on public.competition_events from anon, authenticated;
revoke all on public.competition_results from anon, authenticated;
revoke all on public.gallery_albums from anon, authenticated;
revoke all on public.gallery_photos from anon, authenticated;
revoke all on public.home_content from anon, authenticated;

grant select on public.competition_events to anon, authenticated;
grant select on public.competition_results to anon, authenticated;
grant select on public.gallery_albums to anon, authenticated;
grant select on public.gallery_photos to anon, authenticated;
grant select on public.home_content to anon, authenticated;

grant insert, update, delete on public.competition_events to authenticated;
grant insert, update, delete on public.competition_results to authenticated;
grant insert, update, delete on public.gallery_albums to authenticated;
grant insert, update, delete on public.gallery_photos to authenticated;
grant insert, update on public.home_content to authenticated;

grant usage, select on sequence public.competition_events_id_seq
  to authenticated;
grant usage, select on sequence public.competition_results_id_seq
  to authenticated;
grant usage, select on sequence public.gallery_albums_id_seq
  to authenticated;
grant usage, select on sequence public.gallery_photos_id_seq
  to authenticated;

drop policy if exists "Visitors can read published competition events"
  on public.competition_events;
create policy "Visitors can read published competition events"
on public.competition_events
for select
to anon, authenticated
using (published = true);

drop policy if exists "Admins can manage competition events"
  on public.competition_events;
create policy "Admins can manage competition events"
on public.competition_events
for all
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

drop policy if exists "Visitors can read published competition results"
  on public.competition_results;
create policy "Visitors can read published competition results"
on public.competition_results
for select
to anon, authenticated
using (published = true);

drop policy if exists "Admins can manage competition results"
  on public.competition_results;
create policy "Admins can manage competition results"
on public.competition_results
for all
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

drop policy if exists "Visitors can read published gallery albums"
  on public.gallery_albums;
create policy "Visitors can read published gallery albums"
on public.gallery_albums
for select
to anon, authenticated
using (published = true);

drop policy if exists "Admins can manage gallery albums"
  on public.gallery_albums;
create policy "Admins can manage gallery albums"
on public.gallery_albums
for all
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

drop policy if exists "Visitors can read photos from published gallery albums"
  on public.gallery_photos;
create policy "Visitors can read photos from published gallery albums"
on public.gallery_photos
for select
to anon, authenticated
using (
  exists (
    select 1 from public.gallery_albums
    where gallery_albums.id = gallery_photos.album_id
      and gallery_albums.published = true
  )
);

drop policy if exists "Admins can manage gallery photos"
  on public.gallery_photos;
create policy "Admins can manage gallery photos"
on public.gallery_photos
for all
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

drop policy if exists "Visitors can read home content"
  on public.home_content;
create policy "Visitors can read home content"
on public.home_content
for select
to anon, authenticated
using (id = 1);

drop policy if exists "Admins can create home content"
  on public.home_content;
create policy "Admins can create home content"
on public.home_content
for insert
to authenticated
with check (
  id = 1
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can update home content"
  on public.home_content;
create policy "Admins can update home content"
on public.home_content
for update
to authenticated
using (
  id = 1
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  id = 1
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

-- ---------------------------------------------------------------------------
-- Storage
-- ---------------------------------------------------------------------------

insert into storage.buckets
  (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'gallery-images',
    'gallery-images',
    true,
    5242880,
    array['image/jpeg', 'image/png', 'image/webp']
  ),
  (
    'site-images',
    'site-images',
    true,
    5242880,
    array['image/jpeg', 'image/png', 'image/webp']
  )
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Публичность bucket означает, что известный URL файла доступен напрямую.
-- published=false скрывает альбом из публичных запросов к таблицам, но не
-- является механизмом секретности уже загруженных файлов.
drop policy if exists "Visitors can read site admin images"
  on storage.objects;
create policy "Visitors can read site admin images"
on storage.objects
for select
to anon, authenticated
using (bucket_id in ('gallery-images', 'site-images'));

drop policy if exists "Admins can manage gallery images"
  on storage.objects;
create policy "Admins can manage gallery images"
on storage.objects
for all
to authenticated
using (
  bucket_id = 'gallery-images'
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  bucket_id = 'gallery-images'
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can manage site images"
  on storage.objects;
create policy "Admins can manage site images"
on storage.objects
for all
to authenticated
using (
  bucket_id = 'site-images'
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  bucket_id = 'site-images'
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);
